# Generated by Django 5.2.11 on 2026-04-06 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _ensure_user_profile_table(apps, schema_editor):
    """
    Create user_profile only when missing (legacy DBs may already have it).
    Stub model is built with type() here so makemigrations does not pick it up.
    """
    from django.apps import apps as global_apps
    from django.db import models as dj_models

    table = "user_profile"
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        existing = set(connection.introspection.table_names(cursor=cursor))
    if table in existing:
        return

    app_label, _, model_name = settings.AUTH_USER_MODEL.partition(".")
    user_model = apps.get_model(app_label, model_name)

    stub = type(
        "UserProfileStub",
        (dj_models.Model,),
        {
            "__module__": __name__,
            "Meta": type(
                "Meta",
                (),
                {"app_label": "core", "db_table": table},
            ),
            "id": dj_models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            "is_delete": dj_models.BooleanField(
                db_column="is_delete", default=False
            ),
            "user": dj_models.OneToOneField(
                user_model,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
            ),
        },
    )
    schema_editor.create_model(stub)
    global_apps.all_models["core"].pop("userprofilestub", None)
    global_apps.clear_cache()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="UserProfile",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "is_delete",
                            models.BooleanField(db_column="is_delete", default=False),
                        ),
                        (
                            "user",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="userprofile",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "user_profile",
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _ensure_user_profile_table, migrations.RunPython.noop
                ),
            ],
        ),
    ]
