# Generated by Django 6.0.2 on 2026-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FnolResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'fnol_response',
            },
        ),
    ]
