# Generated by Django 6.0.2 on 2026-02-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRuleMaster',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_type', models.CharField(max_length=50)),
                ('rule_group', models.CharField(max_length=100)),
                ('rule_description', models.TextField()),
                ('rule_expression', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'claim_rule_master',
            },
        ),
        migrations.CreateModel(
            name='ClaimTypeMaster',
            fields=[
                ('claim_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('claim_type_name', models.CharField(max_length=100)),
                ('risk_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'claim_type_master',
            },
        ),
        migrations.CreateModel(
            name='DamageCodeMaster',
            fields=[
                ('damage_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('damage_type', models.CharField(max_length=100)),
                ('severity_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'damage_code_master',
            },
        ),
    ]
