# Generated by Django

from django.db import migrations, models


def set_risk_ranges(apps, schema_editor):
    """Set risk_min and risk_max for standard claim types."""
    ClaimTypeMaster = apps.get_model("claims", "ClaimTypeMaster")
    ranges = {
        "SIMPLE": (0, 50),
        "MEDIUM": (51, 75),
        "COMPLEX": (76, 100),
    }
    for ct in ClaimTypeMaster.objects.all():
        name_upper = (ct.claim_type_name or "").strip().upper()
        if name_upper in ranges:
            ct.risk_min, ct.risk_max = ranges[name_upper]
            ct.save()


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0004_add_llm_response_to_claim_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimtypemaster",
            name="risk_min",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="claimtypemaster",
            name="risk_max",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.RunPython(set_risk_ranges, migrations.RunPython.noop),
    ]
