from django.urls import path

from .views import (
    bulk_delete_fnol,
    get_fnol,
    get_claim_evaluation,
    health_check,
    list_fnol,
    list_fraud_claims,
    login,
    process_claim,
    recommendation_report_pdf,
    business_rule_validation_report_pdf,
    run_fraud_detection,
    save_fnol,
    create_user,
    list_users,
    edit_user,
    change_role,
    reset_password,
    deactivate_user,
    activate_user,
    soft_delete_user,
    claim_type_master_collection,
    claim_type_master_detail,
    claim_rule_master_collection,
    claim_rule_master_detail,
    damage_code_master_collection,
    damage_code_master_detail,
    pricing_config_collection,
    pricing_config_detail,
    business_rule_validation_failed_report_pdf,
)
from .digitization_views import (
    digitization_upload,
    digitization_classify,
    digitization_extract,
    digitization_list_extractions,
    digitization_extract_kv,
    digitization_save_classified_local,
    digitization_save_invoice_details,
    digitization_verify_parts,
    digitization_add_part_to_master,
    invoice_history_list,
    invoice_history_detail,
    digitization_files_summary,
)
from .phase1_views import (
    image_fraud_analysis,
    image_fraud_results,
    duplicate_candidates,
    damage_assessment_detailed,
    total_value,
)
from .phase2_views import (
    invoice_analyze,
    pricing_explain,
    reasoning_summary,
)
from .phase3_views import (
    batch_validate_claims,
    video_analyze,
)
from .card_insight_views import (
    damage_assessment_card_details,
    damage_assessment_card_refresh,
    damage_assessment_cards,
)
from .video_views import (
    video_assets_collection,
    video_damage_assessment,
    video_job_detail,
    video_jobs_collection,
    video_results,
    video_timeline,
)

urlpatterns = [
    path("health", health_check, name="health_check"),
    path("login", login, name="login"),
    path("batch/validate", batch_validate_claims, name="batch_validate_claims"),
    path("claims/<str:complaint_id>/pricing/explain", pricing_explain, name="pricing_explain"),
    path("claims/<str:complaint_id>/invoice/analyze", invoice_analyze, name="invoice_analyze"),
    path("claims/<str:complaint_id>/reasoning/summary", reasoning_summary, name="reasoning_summary"),
    path("claims/<str:complaint_id>/video/analyze", video_analyze, name="video_analyze"),
    path("claims/<str:complaint_id>/video/assets", video_assets_collection, name="video_assets_collection"),
    path("claims/<str:complaint_id>/video/jobs", video_jobs_collection, name="video_jobs_collection"),
    path("claims/<str:complaint_id>/video/jobs/<int:job_id>", video_job_detail, name="video_job_detail"),
    path("claims/<str:complaint_id>/video/results", video_results, name="video_results"),
    path("claims/<str:complaint_id>/video/timeline", video_timeline, name="video_timeline"),
    path("claims/<str:complaint_id>/timeline", video_analyze, name="claim_timeline"),
    path("users/", list_users, name="list_users"),
    path("users/create", create_user, name="create_user"),
    path("users/<int:pk>/", edit_user, name="edit_user"),
    path("users/<int:pk>/change-role/", change_role, name="change_role"),
    path("users/<int:pk>/reset-password/", reset_password, name="reset_password"),
    path("users/<int:pk>/deactivate/", deactivate_user, name="deactivate_user"),
    path("users/<int:pk>/activate/", activate_user, name="activate_user"),
    path("users/<int:pk>/soft-delete/", soft_delete_user, name="soft_delete_user"),
    path("save-fnol", save_fnol, name="save_fnol"),
    path("process-claim", process_claim, name="process_claim"),
    path("fnol/<str:complaint_id>/run-fraud-detection", run_fraud_detection, name="run_fraud_detection"),
    path("fraud-claims", list_fraud_claims, name="list_fraud_claims"),
    path("fnol", list_fnol, name="list_fnol"),
    path("fnol/bulk-delete/", bulk_delete_fnol, name="bulk_delete_fnol_slash"),
    path("fnol/bulk-delete", bulk_delete_fnol, name="bulk_delete_fnol"),
    path("fnol/<str:complaint_id>/evaluation", get_claim_evaluation, name="get_claim_evaluation"),
    path("fnol/<str:complaint_id>/recommendation-report/", recommendation_report_pdf, name="recommendation_report_pdf"),
    path("fnol/<str:complaint_id>/brv-report/", business_rule_validation_report_pdf, name="business_rule_validation_report_pdf"),
    path("fnol/<str:complaint_id>/brv-failed-report/", business_rule_validation_failed_report_pdf, name="business_rule_validation_failed_report_pdf"),
    path("fnol/<str:pk>/", get_fnol, name="get_fnol"),
    # Same view without trailing slash (avoids 301 redirect when clients do not follow redirects with auth)
    path("fnol/<str:pk>", get_fnol, name="get_fnol_no_slash"),

    # Master tables CRUD
    path("masters/claim-types", claim_type_master_collection, name="claim_type_master_collection"),
    path("masters/claim-types/<int:pk>", claim_type_master_detail, name="claim_type_master_detail"),
    path("masters/claim-rules", claim_rule_master_collection, name="claim_rule_master_collection"),
    path("masters/claim-rules/<int:pk>", claim_rule_master_detail, name="claim_rule_master_detail"),
    path("masters/damage-codes", damage_code_master_collection, name="damage_code_master_collection"),
    path("masters/damage-codes/<int:pk>", damage_code_master_detail, name="damage_code_master_detail"),
    path("masters/pricing-config", pricing_config_collection, name="pricing_config_collection"),
    path("masters/pricing-config/<int:pk>", pricing_config_detail, name="pricing_config_detail"),

    # Claim digitization workflow
    path("digitization/upload", digitization_upload, name="digitization_upload"),
    path("digitization/classify", digitization_classify, name="digitization_classify"),
    path("digitization/extract", digitization_extract, name="digitization_extract"),
    path("digitization/list-extractions", digitization_list_extractions, name="digitization_list_extractions"),
    path("digitization/extract-kv", digitization_extract_kv, name="digitization_extract_kv"),
    path("digitization/save-classified-local", digitization_save_classified_local, name="digitization_save_classified_local"),
    path("digitization/save-invoice-details", digitization_save_invoice_details, name="digitization_save_invoice_details"),
    path("digitization/verify-parts", digitization_verify_parts, name="digitization_verify_parts"),
    path("digitization/add-part-to-master", digitization_add_part_to_master, name="digitization_add_part_to_master"),
    path("invoice-history", invoice_history_list, name="invoice_history_list"),
    path("invoice-history/<str:claim_number>", invoice_history_detail, name="invoice_history_detail"),
    path("digitization/files-summary", digitization_files_summary, name="digitization_files_summary"),

    # FNOL-scoped: image fraud, damage breakdown, valuation
    path("fnol/<str:complaint_id>/image-fraud-analysis", image_fraud_analysis, name="image_fraud_analysis"),
    path("fnol/<str:complaint_id>/image-fraud-results", image_fraud_results, name="image_fraud_results"),
    path("fnol/<str:complaint_id>/duplicate-candidates", duplicate_candidates, name="duplicate_candidates"),
    path(
        "fnol/<str:complaint_id>/damage-assessment/cards/<str:card_key>/refresh",
        damage_assessment_card_refresh,
        name="damage_assessment_card_refresh",
    ),
    path(
        "fnol/<str:complaint_id>/damage-assessment/cards/<str:card_key>/details",
        damage_assessment_card_details,
        name="damage_assessment_card_details",
    ),
    path(
        "fnol/<str:complaint_id>/damage-assessment/cards",
        damage_assessment_cards,
        name="damage_assessment_cards",
    ),
    path("fnol/<str:complaint_id>/damage-assessment-detailed", damage_assessment_detailed, name="damage_assessment_detailed"),
    path("fnol/<str:complaint_id>/video-damage-assessment", video_damage_assessment, name="video_damage_assessment"),
    path("fnol/<str:complaint_id>/total-value", total_value, name="total_value"),
]
